public enum Error {
    __NO_ERROR__,
    __FILE_NOT_FOUND_EXCEPTION__,
    __FILE_TOO_LONG_EXCEPTION__,
    __SYNTAX_ERROR_UNCLOSED_CONTAINER_EXCEPTION__,
    __SYNTAX_ERROR_INCOMPLETE_PARAMITER_EXCEPTION__,
    __SYNTAX_ERROR_TOO_MANY_TOKENS__,
}